name: Multi-Job Workflows
on: push

jobs:
    batch_job_1:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout repo
          uses: actions/checkout@v4

        - name: Run shell Script
          run: |
            chmod +x action.sh
            ./action.sh
        
    test_job_2:
        needs: batch_job_1
        runs-on: ubuntu-latest
        steps:
        - name: sleep for 10 second
          run: sleep 10
        - name: Check file
          run: grep -i "dragon" dragon.txt

    deploy_job_3:
        needs: [test_job_2]
        runs-on: ubuntu-latest
        steps:
        - name: sleep for 10 second
          run: sleep 5

        - name: Read file
          run: cat dragon.txt